### ISSUE TITLE
error when run PsiDetect.R

### ISSUE THREAD

**Issue by ssscj** [RouhanifardLab/PsiNanopore#2]
Hi,
thanks for developing PsiNanopore. I aligned the direct RNA reads to the transcriptome reference, and run the PsiDetect.R, then it rasied this error:
```
Error in paste(kmer, res.df.new, sep = "") :
  object 'res.df.new' not found
Calls: paste -> standardGeneric -> eval -> eval -> eval
Execution halted
```
I checked the codes in PsiDetect.R, in line 100-107, which caused the error 
```
refbase <- as.data.frame(refbase)$x
    refbase.new = refbase
    if (refbase == "A" & res.df$strand[i] == "-"){res.df.new = "T"}
    if (refbase == "T" & res.df$strand[i] == "-"){res.df.new = "A"}
    if (refbase == "C" & res.df$strand[i] == "-"){res.df.new = "G"}
    if (refbase == "G" & res.df$strand[i] == "-"){res.df.new = "C"}

    kmer = paste(kmer,res.df.new,sep = "")
```
I think maybe `refbase.new = refbase` should be `res.df.new = refbase`

Best regards,
Chujie

**Comment by RouhanifardLab** [comment]
Hi -- we have updated the code with step-by-step instructions. The update is under the pathway:

[RouhanifardLab/PsiNanopore/Pvalue-Pipeline](https://github.com/RouhanifardLab/PsiNanopore/tree/fbb18edb63f907e7585d737761b07f868309c7cf/Pvalue-Pipeline)

Let us know if you have any questions!
