### ISSUE TITLE
'seqnames' must have the length of the object to construct (1) or   length 1

### ISSUE THREAD

**Issue by itslittman** [RouhanifardLab/PsiNanopore#3]
I ran PsiDetect.R and got this error after the pileups:

[1] "Done with pileup!"
[1] "------------------------------------"
[1] "Started assigning kmers..."
Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or
  length 1
Calls: GRanges -> new_GRanges -> stop_if_wrong_length
Execution halted

Any help is appreciated!
noah

**Comment by RouhanifardLab** [comment]
Hi Noah!
Thanks for your note -- we are aware of this issue on our end and are currently working on updating the code. It should be up in the next week or so.

Thanks!
Caroline 
--------------------
_PhD Candidate_
**Rouhanifard Lab**

**Comment by RouhanifardLab** [comment]
Hi Noah!
Thanks for your note -- we are aware of this issue on our end and are currently working on updating the code. It should be up in the next week or so.

Thanks!
Caroline 

_PhD Candidate_
**Rouhanifard Lab**

**Comment by itslittman** [comment]
@RouhanifardLab okay thank you

**Comment by itslittman** [comment]
@RouhanifardLab it's still giving the error, any updates?

**Comment by septav** [comment]
Hi @itslittman!

Thank you for your comment. I wanted to inquire if it would be possible for you to share a small subset of your bam file so that we can check it from our end. Additionally, could you please let me know which operating system you are using?

Thank you!

**Comment by RouhanifardLab** [comment]
Hi -- we have updated the code with step-by-step instructions. The update is under the pathway:

[RouhanifardLab/PsiNanopore/Pvalue-Pipeline](https://github.com/RouhanifardLab/PsiNanopore/tree/fbb18edb63f907e7585d737761b07f868309c7cf/Pvalue-Pipeline)

Let us know if you have any questions!
